name: Update page lists

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  test:
    runs-on: [self-hosted, linux, x64, amcTrivial-AoPS-updater]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: node downloadlists.js
      - run: |
          git config user.name "vqbc"
          git config user.email "andrewggchang@gmail.com"
          git add -A
          if git diff --cached --quiet; then
            echo "there is no page list changes to comit."
          else
            git commit -m "update page list"
            git push
          fi
